Add documentation to the struct fields and functions of the API of ma…
beehive-lab/mambo pull request #115
Opened 2024-02-19 21:47 UTC by mskordal

…mbo used in the tutorial or exercise 1.

Doxygen-style documentation isa added. Namely, the following fields of struct code_ctx are documented: void *read_address
int inst
void *write_p

And the following functions:
mambo_context *mambo_register_plugin(void)
int mambo_register_pre_basic_block_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_post_basic_block_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_pre_thread_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_post_thread_cb(mambo_context *ctx, mambo_callback cb) void *mambo_get_source_addr(mambo_context *ctx)
int mambo_get_thread_id(mambo_context *ctx)

In mambo_get_thread_id the precondition that ctx->thread_data should not be null is added, to avoid calling the function during the constructor and cause segfault.

2024-02-20 13:47 UTC, IgWod commented on api/plugin_support.h
> + * Registers a callback function to a mambo plugin described by its context.
Again: described

2024-02-20 13:47 UTC, IgWod commented on api/plugin_support.h
> + * @param ctx The context that describes the plugin.
Again: describes

2024-02-20 13:48 UTC, IgWod commented on api/plugin_support.h
> + * @brief Registers a callback function to a mambo plugin that is called onece
Same as above.

2024-02-20 13:50 UTC, IgWod commented on api/plugin_support.h
> + * currently being scanned by mambo using the plugin's context.
Plugin context doesn't scan instructions. Scanner (shared between all plugins) does. Context just holds the state of MAMBO exposing information from the scanner.

2024-02-20 13:50 UTC, IgWod commented on api/plugin_support.h
> + * @param ctx The context that describes the plugin.
Again: describes

2024-02-20 13:53 UTC, IgWod commented on api/plugin_support.h
> + * @brief Returns the id of the active thread.
I wouldn't say active thread as many threads can execute at the same time. We should say something along the lines: ID of the thread where the callback was called?

2024-02-20 13:53 UTC, IgWod commented on api/plugin_support.h
> + * @param ctx The context that describes a plugin.
Again: describes

2024-02-23 12:25 UTC, mskordal commented on api/plugin_support.h
> + * for an event of "plugin registration" type. Each mambo context created
Can we say that the context holds the plugin state? Cause it sets the context with the value PLUGIN_REG

2024-02-23 12:29 UTC, mskordal commented on api/plugin_support.h
> + * @brief Registers a callback function to a mambo plugin that is called once
I state that the callback is called once, before or after a bb is scanned. If it is scanned many times, it will be scanned once for each time

2024-02-23 12:33 UTC, mskordal commented on api/plugin_support.h
> + * describes a unique mambo plugin.
shall we write then that the plugin holds the plugin state, the MAMBO state or both?

2024-02-26 14:46 UTC, IgWod requested changes
Thank you for addressing the feedback. I have few more comments just to polish things a bit more. I think this will be the last rounds of comments from me.

2024-02-26 14:46 UTC, IgWod commented on api/plugin_support.h
> +  int inst; ///< Enum indication of the decoded instruction's type.
indicating?

2024-02-26 14:46 UTC, IgWod commented on api/plugin_support.h
> + * Registers a new mambo plugin and allocates a new mambo context A mambo
Mix of "MAMBO" and "mambo". Please make it uniform. And missing dot after context.

2024-02-26 14:46 UTC, IgWod commented on api/plugin_support.h
> + * before each basic block (single-entry - single-exit code region), is scanned.
Unnecessary comma at the end?

2024-02-26 14:46 UTC, IgWod commented on api/plugin_support.h
> + * @brief Registers a callback function to a mambo plugin that is called every
Same comments as for the pre_ callback apply.

2024-02-26 14:46 UTC, IgWod commented on api/plugin_support.h
> + * @return the untranslated instruction address.
Capitalise "the"?

2024-02-26 16:08 UTC, closed without merging