Add documentation to the struct fields and functions of the API of ma…
beehive-lab/mambo pull request #116
Opened 2024-02-26 16:07 UTC by mskordal

…mbo used in the tutorial or exercise 1.

Continuation of #115 

Namely, the following fields of struct code_ctx are documented: void *read_address
int inst
void *write_p

And the following functions:
mambo_context *mambo_register_plugin(void)
int mambo_register_pre_basic_block_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_post_basic_block_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_pre_thread_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_post_thread_cb(mambo_context *ctx, mambo_callback cb) void *mambo_get_source_addr(mambo_context *ctx)
int mambo_get_thread_id(mambo_context *ctx)

In mambo_get_thread_id the precondition that ctx->thread_data should not be null is added, to avoid calling the function during the constructor and cause segfault.

Add documentation to the struct fields and functions of the API of mambo used in the tutorial or exercise 1.

Namely, the following fields of struct code_ctx are documented: void *read_address
int inst
void *write_p

And the following functions:
mambo_context *mambo_register_plugin(void)
int mambo_register_pre_basic_block_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_post_basic_block_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_pre_thread_cb(mambo_context *ctx, mambo_callback cb) int mambo_register_post_thread_cb(mambo_context *ctx, mambo_callback cb) void *mambo_get_source_addr(mambo_context *ctx)
int mambo_get_thread_id(mambo_context *ctx)

In mambo_get_thread_id the precondition that ctx->thread_data should not be null is added, to avoid calling the function during the constructor and cause segfault.

2024-02-26 16:22 UTC, IgWod reviewed
Thanks! For addressing my latests comments. I found one more typo. I added @jkressel to have a look as well.

2024-02-26 16:22 UTC, IgWod commented on api/plugin_support.h
> + * @brief Registers a callback function to a MAMBO plugin that is called onece
Typo "onece"

2024-02-29 14:47 UTC, jkressel requested changes
Just a few nit-picks, but after that I'm happy for it to be merged. Thanks!

2024-02-29 14:47 UTC, jkressel commented on api/plugin_support.h
> + * Registers a new MAMBO plugin and allocates a new MAMBO context A MAMBO
context. A MAMBO ...

2024-02-29 14:47 UTC, jkressel commented on api/plugin_support.h
> + * time, when the trace is created, and after the code cache is flushed and
when a trace is created

2024-02-29 14:47 UTC, jkressel commented on api/plugin_support.h
> + * block needs to execute.
the block

2024-02-29 14:47 UTC, jkressel commented on api/plugin_support.h
> + * time, when the trace is created, and after the code cache is flushed and
a trace

2024-02-29 14:47 UTC, jkressel commented on api/plugin_support.h
> + * block needs to execute.
the block

2024-03-12 12:16 UTC, merged