Add data race detector plugin
beehive-lab/mambo pull request #130
Opened 2024-07-31 18:42 UTC by AlphaDaze

This PR adds a data race detector plugin. This plugin detects possible data races within the underlying program along with information that can be utilised for debugging.

The README provides further context for the plugin and its usage.

Compile with `make datarace_ft` and run with `mambo_datarace_ft`. The plugin includes two algorithms which can be compiled separately: `fasttrack` and `djit`. Both are happens-before algorithms with `fasttrack` being an improvement over `djit` with both memory and runtime.

All comments and suggestions are welcome!

**Sample output**

```
--- FORK: Thread 1029188 created by 0
--- LOCK: Thread 1029188 locked 0x7fff22128b10
--- UNLOCK: Thread 1029188 unlocked 0x7fff22128b10
--- FORK: Thread 1029189 created by 1029188
--- LOCK: Thread 1029188 locked 0x7fff22128b10
--- UNLOCK: Thread 1029188 unlocked 0x7fff22128b10
--- FORK: Thread 1029223 created by 1029188
--- JOIN: Thread 1029189 joining 1029188
!!! READ RACE: Possible read race - 0x41104c by thread 1029223
>>>> at 0x40074c: /home/vaz/Documents/git/helgrind_tests/hg04_race (0x400744) (th10)
!!! WRITE RACE: Possible write race - 0x41104c by thread 1029223
>>>> at 0x40075c: /home/vaz/Documents/git/helgrind_tests/hg04_race (0x400744) (th10)
--- JOIN: Thread 1029223 joining 1029188
--- LOCK: Thread 1029188 locked 0x7fff22128ab0
--- UNLOCK: Thread 1029188 unlocked 0x7fff22128ab0
We're done; exiting with status: 0
```

2024-08-02 16:01 UTC, IgWod requested changes
Hi @AlphaDaze,

Thank you for your contribution. It looks good, however there are few things I'd like to be addressed before merging it. Please see attached comments.

Also, a major point, please remove any commented out code or add explanation why it's commend out and how it can be used in the future. We don't need any dead code in the repo :).

Let me know if something is unclear.

Many thanks,
Igor

2024-08-03 23:35 UTC, AlphaDaze commented on dbm.h
> +  void *shared_plugin_data;
I agree. Renamed to `shared_parent_data`.

2024-08-03 23:46 UTC, AlphaDaze commented on plugins/datarace/README.md
> +> **Note:** Underlying programs must be compiled with `-no-pie` (statically or dynamically) OR must be dynamically compiled and mambo compiled with `NO_PIE_ENABLE` disabled in [datarace.h](datarace.h
Whoops... Fixed

2024-08-03 23:47 UTC, AlphaDaze commented on plugins/datarace/README.md
> +Test applications utilising multiple threads have been provided in the plugins/datarace/test/ directory. TODO
Removed

2024-08-03 23:47 UTC, AlphaDaze commented on plugins/datarace/README.md
> +> To compile and use the DJIT+ implementation, use `make datarace_ft` and run with `./mambo_datarace_djit`.
Yup, fixed

2024-08-03 23:47 UTC, AlphaDaze commented on plugins/datarace/README.md
> +[datarace.h](datarace.h) contains option to enable `no-pie` to properly ignore clib. More debug information can also be enabled.
Let's pretend I didn't make that mistake...multiple times 🙈

2024-08-03 23:47 UTC, AlphaDaze commented on plugins/datarace/README.md
> +Currently clib is ignored by not processing any reads/writes to addresses above `0x7000000000` which require the underlying program to be compiled with `no-pie`. A workaround has been retrieve the lo
Rephrased, let me know if it's still unclear please

2024-08-03 23:48 UTC, AlphaDaze commented on plugins/datarace/datarace.c
> +    emit_push(ctx, (1 << 0) | (1 << 1) | (1 << 2) | (1 << 3));
Changed throughout

2024-08-03 23:48 UTC, AlphaDaze commented on plugins/datarace/datarace.c
> +  set_cb = mambo_register_function_cb(ctx, "pthread_mutex_lock",
Changed indentation for function callbacks

2024-08-03 23:48 UTC, AlphaDaze commented on plugins/datarace/datarace.h
> +  pthread_mutex_t *mutex; // change this to address val?
Removed comment

2024-08-06 14:49 UTC, IgWod requested changes
Thanks for addressing the comments. I found two more small issues, but I'm happy otherwise. Please either remove the commented out code I highlighted or add TODO/explanation why it's commented out.

The other things is commit messages. Could you please clean it up? Ideally we would like to have two commits. The first commit for changes to the core and then the second one adding the plugin. Shouldn't be too difficult to achieve with `git rebase -i` and some amending.

Once that's done I'm happy with the PR, but I'll ask @jkressel to have a look as well, and once he approves it we can merge it.

2024-08-06 14:49 UTC, IgWod commented on plugins/datarace/datarace.c
> +  // info("Processing: READ(%lx): %u %p\n", inst_addr, tid, ld_addr);
Why is it commented out?

2024-08-06 14:49 UTC, IgWod commented on plugins/datarace/datarace.c
> +  // info("Processing: WRITE(%lx): %u %p\n", inst_addr, tid, st_addr);
Again, why is it commented out?

2024-08-07 21:08 UTC, AlphaDaze commented on plugins/datarace/datarace.c
> +  // info("Processing: READ(%lx): %u %p\n", inst_addr, tid, ld_addr);
Uncommented and changed to debug output

2024-08-07 21:08 UTC, AlphaDaze commented on plugins/datarace/datarace.c
> +  // info("Processing: WRITE(%lx): %u %p\n", inst_addr, tid, st_addr);
Uncommented and changed to debug output

2024-08-07 21:14 UTC, AlphaDaze commented
Sounds good! Thanks for taking a look at it. I have rebased and squashed the relevant commits together as requested.

If there is any other changes (however small), please do let me know.

2024-08-09 10:11 UTC, josh-nook commented
Looks good to me

2024-08-09 10:19 UTC, IgWod commented
Looks good to me! I'll ask @jkressel to have a look now.

2024-08-09 10:23 UTC, jkressel approved these changes
Looks good to me, I'm happy to merge.

2024-08-09 10:23 UTC, merged