Immediate Jump Linking on RISC-V
beehive-lab/mambo pull request #63
Opened 2021-11-02 14:33 UTC by jkressel

I have tested on a number of programs including GZip, gcc, OpenSSL SHA256 and have found the performance increase to be between 7-56% depending on the application.

2021-11-04 18:38 UTC, lgeek requested changes

2021-11-04 18:38 UTC, lgeek commented on arch/riscv/dispatcher_riscv.c
> +      intptr_t offset = (block_address+6) - (intptr_t)branch_addr;
`riscv_link_to()` already implements this logic. You just need something like:

```
dbm_code_cache_meta *bb_meta = &thread_data->code_cache_meta[bb_id];
uint16_t *branch_addr = bb_meta->exit_branch_addr;
int ret = riscv_link_to(&branch_addr, block_address);
assert(ret == 0);
__clear_cache(bb_meta->exit_branch_addr, branch_addr);
```

2021-11-04 18:38 UTC, lgeek commented on arch/riscv/scanner_riscv.c
> +void riscv_cc_jump(dbm_thread *thread_data, uint16_t *write_p, uintptr_t target) {
So we don't need this function

2021-11-04 20:35 UTC, jkressel commented
@lgeek I've made the requested changes

2021-11-10 15:31 UTC, lgeek commented
Merged in cf2da8b.

Once again, if you're declaring variables in a `switch` `case`, you need to wrap the code in curly brackets to turn it into a statement where you're allowed to declare variables. Not sure if you're forgetting to check that the code compiles (and works) or if you're using a compiler that doesn't throw a warning or error for this?

2021-11-10 15:31 UTC, closed without merging